### ISSUE TITLE
Mobile View: CSS for Community Resources

### ISSUE THREAD

**Issue by rcass** [redacademy/vatjss-summer-2017#20]
When community resources is clicked, the submenu expands seems to extend past the view port (horizontally).

Here is a screenshot:
![screen shot 2017-09-18 at 11 54 15 am](https://user-images.githubusercontent.com/5028555/30559108-60d33fee-9c68-11e7-8eaa-6c5f0f91ae5a.png)

Notice that lack of rounded corners on the right side.

**Comment by rcass** [comment]
Still appearing cut off on the staging site (aka the rounded corners should be on all four corners not just the left side).

![screen shot 2017-09-18 at 10 40 13 pm](https://user-images.githubusercontent.com/5028555/30577332-5dea3364-9cc2-11e7-951b-8f0bbb424077.png)

**Comment by CamdenShaw** [comment]
Bobby pushed the fixes to the staging site now.  Next time you check it should be there :)

**Comment by rcass** [comment]
I see those changes now! Great 👍
