### ISSUE TITLE
Mobile View: Long Resources Titles cut off

### ISSUE THREAD

**Issue by rcass** [redacademy/vatjss-summer-2017#21]
In mobile, resources with long names are cut off and unreadable.

![screen shot 2017-09-18 at 11 57 49 am](https://user-images.githubusercontent.com/5028555/30559252-e395b4ac-9c68-11e7-9f54-8e8d23118462.png)

**Comment by rcass** [comment]
I am sill seeing this issue on the staging site :/

![screen shot 2017-09-18 at 10 37 16 pm](https://user-images.githubusercontent.com/5028555/30577266-0a53a668-9cc2-11e7-8e9f-094823f81bf0.png)

**Comment by CamdenShaw** [comment]
Bobby hasn't pushed my fix to staging site yet, but I did fix it...

**Comment by rcass** [comment]
Yay I see the changes now 👍
